version: "3.3"
services:
  torture:
    image: meetrix/jitsi-meet-torture
  hub:
    image: selenium/hub:3.141.59
  node:
    build: ./node
    image: meetrix/jitsi-meet-torture-selenium-node
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub